// Exhaustive verification of the state machines of the shared model.
//   node --max-old-space-size=14000 verify.js [outDir]
// For each setup and fault class it builds the abstract model (src/cell-verify.js), explores every
// reachable state, checks the properties of M.PROPERTIES and writes
//   cell_setupN_<faults>.smv   the same model for NuSMV (run with: NuSMV -dynamic file.smv)
//   results.md / results.json  states, properties, unreachable states, counterexample traces
// If NuSMV is on the PATH (or in the NUSMV environment variable) the .smv files are checked too.
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const M = require('./src/cell-model.js');
const V = require('./src/cell-verify.js');

const OUT = process.argv[2] || path.join(__dirname, 'out', 'verification');
fs.mkdirSync(OUT, { recursive: true });
const RUNS = [];
[1, 2].forEach((setup) => ['none', 'sensor', 'process'].forEach((faults) => RUNS.push({ setup, faults })));
// ONLY=setup2_sensor,... re-runs some analyses and keeps the others from the last results.json
const ONLY = process.env.ONLY ? process.env.ONLY.split(',') : null;
let results = [];
if ((ONLY || process.env.REPORT_ONLY) && fs.existsSync(path.join(OUT, 'results.json'))) results = JSON.parse(fs.readFileSync(path.join(OUT, 'results.json'), 'utf8')).filter((x) => process.env.REPORT_ONLY || !ONLY.includes(x.tag));
const lint = M.lint();
if (lint.length) { console.error('model lint failed:\n' + lint.join('\n')); process.exit(1); }

for (const run of RUNS) {
  const tag = `setup${run.setup}_${run.faults}`;
  if (ONLY && !ONLY.includes(tag)) continue;
  if (process.env.REPORT_ONLY) continue;          // only rewrite results.md from results.json
  const ir = V.build(run.setup, { faults: run.faults === 'none' ? false : run.faults });
  const smv = V.toSmv(ir);
  const smvFile = `cell_${tag}.smv`;
  fs.writeFileSync(path.join(OUT, smvFile), smv);
  process.stdout.write(`${tag}: ${ir.vars.length} variables, ${ir.cmds.length} commands ... `);
  const t0 = Date.now();
  const r = V.check(ir, { maxStates: 30e6 });
  console.log(`${r.states} states, ${r.edges} transitions, ${((Date.now() - t0) / 1000).toFixed(1)} s, ${r.results.filter((x) => !x.ok).length} failed, ${r.deadlocks} deadlocks`);
  results.push({ tag, setup: run.setup, faults: run.faults, vars: ir.vars.length, commands: ir.cmds.length, smv: smvFile, states: r.states, edges: r.edges, seconds: (Date.now() - t0) / 1000, deadlocks: r.deadlocks, deadlock: r.deadlock, unreached: r.unreached, props: r.results });
}
const order = RUNS.map((x) => `setup${x.setup}_${x.faults}`);
results.sort((a, b) => order.indexOf(a.tag) - order.indexOf(b.tag));

// optional: NuSMV on the generated files
let nusmv = process.env.NUSMV || null;
if (!nusmv) { try { execFileSync(process.platform === 'win32' ? 'where' : 'which', ['NuSMV'], { stdio: 'pipe' }); nusmv = 'NuSMV'; } catch (e) { /* not installed */ } }
const nusmvOut = {};
if (nusmv) {
  results.forEach((x) => {
    try { nusmvOut[x.tag] = execFileSync(nusmv, ['-dynamic', path.join(OUT, x.smv)], { encoding: 'utf8', maxBuffer: 1 << 26, timeout: 3600e3 }); }
    catch (e) { nusmvOut[x.tag] = 'NuSMV failed: ' + (e.stdout || e.message); }
    fs.writeFileSync(path.join(OUT, x.smv.replace('.smv', '.nusmv.txt')), nusmvOut[x.tag]);
  });
}

// report
const L = [];
const FAULTS = { none: 'nominal operation', sensor: 'camera / proximity mismatches and camera faults', process: 'missed picks, confirmation timeouts, transport timers' };
const faultText = (x) => FAULTS[x.faults] + (x.faults === 'process' && x.setup === 2 ? ', undersized parts' : '');
L.push('# Verification of the cell state machines');
L.push('');
L.push(`Generated by \`source/verify.js\` from \`source/src/cell-model.js\` on ${new Date().toISOString().slice(0, 10)}.`);
L.push('The abstract model contains the four state machines exactly as written in the model (every state and step is a location, every guard a command guard). The plant is abstract: no step times, jobs finish in any order, the CNC, the belt and the operator move nondeterministically, and the output pallet holds 2 parts instead of 12. Every reachable state was explored. Safety properties (P) were checked in every stable state or at every start of the named jobs; liveness properties (L) mean that from every reachable state the goal can still be reached (no deadlock and no livelock), assuming the operator eventually does what the HMI asks.');
L.push('');
L.push('| Run | Faults | States | Transitions | Time | Deadlocks | Failed properties |');
L.push('|---|---|---:|---:|---:|---:|---|');
results.forEach((x) => L.push(`| Setup ${x.setup} | ${faultText(x)} | ${x.states.toLocaleString('en-US')} | ${x.edges.toLocaleString('en-US')} | ${x.seconds.toFixed(1)} s | ${x.deadlocks} | ${x.props.filter((p) => !p.ok).map((p) => p.id).join(', ') || 'none'} |`));
L.push('');
L.push('## Properties');
L.push('');
L.push('| Id | Property | ' + results.map((x) => `S${x.setup} ${x.faults}`).join(' | ') + ' |');
L.push('|---|---|' + results.map(() => ':-:').join('|') + '|');
M.PROPERTIES.forEach((p) => {
  L.push(`| ${p.id} | ${p.text} | ` + results.map((x) => { const q = x.props.find((y) => y.id === p.id); return q ? (q.ok ? 'pass' : '**FAIL**') : '–'; }).join(' | ') + ' |');
});
L.push('');
L.push('## States that were never reached');
L.push('');
results.forEach((x) => {
  const u = Object.entries(x.unreached).filter(([, v]) => v.length).map(([k, v]) => `${k}: ${v.join(', ')}`).join('; ');
  L.push(`- Setup ${x.setup}, ${x.faults}: ${u || 'none'}`);
});
L.push('');
const fails = results.flatMap((x) => x.props.filter((p) => !p.ok).map((p) => ({ x, p })));
if (fails.length || results.some((x) => x.deadlock)) {
  L.push('## Counterexamples');
  fails.forEach(({ x, p }) => { L.push('', `### Setup ${x.setup}, ${x.faults}: ${p.id} ${p.text}`, '', '```', ...p.trace.map((s, i) => `${i + 1}. ${s}`), '```'); });
  results.filter((x) => x.deadlock).forEach((x) => { L.push('', `### Setup ${x.setup}, ${x.faults}: deadlock`, '', '```', ...x.deadlock.trace.map((s, i) => `${i + 1}. ${s}`), '```'); });
  L.push('');
}
L.push('## Files');
L.push('');
results.forEach((x) => L.push(`- \`${x.smv}\`: NuSMV model, ${x.vars} variables, ${x.commands} commands${nusmv ? ' (NuSMV output in `' + x.smv.replace('.smv', '.nusmv.txt') + '`)' : ''}`));
if (!nusmv) L.push('', 'NuSMV was not installed when this report was generated; the `.smv` files can be checked with `NuSMV -dynamic <file>`.');
fs.writeFileSync(path.join(OUT, 'results.md'), L.join('\n') + '\n');
fs.writeFileSync(path.join(OUT, 'results.json'), JSON.stringify(results, null, 1));
console.log('written', path.join(OUT, 'results.md'));
if (fails.length || results.some((x) => x.deadlocks)) process.exitCode = 1;
